-- Seed data from training_updated.xlsx
-- Run this in Supabase SQL editor

-- 1. Course
INSERT INTO courses (name, icon, colour_hex, sort_order, status) VALUES ('Sales Mastery', '◈', '#C9A96E', 100, 'active') ON CONFLICT (name) DO UPDATE SET sort_order = EXCLUDED.sort_order;

-- 2. Categories
INSERT INTO categories (title, description, course_id) VALUES ('Introduction', '', (SELECT id FROM courses WHERE name = 'Sales Mastery'));
INSERT INTO categories (title, description, course_id) VALUES ('CRM', '', (SELECT id FROM courses WHERE name = 'Sales Mastery'));
INSERT INTO categories (title, description, course_id) VALUES ('ECHO', '', (SELECT id FROM courses WHERE name = 'Sales Mastery'));
INSERT INTO categories (title, description, course_id) VALUES ('Product', '', (SELECT id FROM courses WHERE name = 'Sales Mastery'));
INSERT INTO categories (title, description, course_id) VALUES ('CROP', '', (SELECT id FROM courses WHERE name = 'Sales Mastery'));
INSERT INTO categories (title, description, course_id) VALUES ('GORA', '', (SELECT id FROM courses WHERE name = 'Sales Mastery'));
INSERT INTO categories (title, description, course_id) VALUES ('RLS', '', (SELECT id FROM courses WHERE name = 'Sales Mastery'));
INSERT INTO categories (title, description, course_id) VALUES ('Conclusion', '', (SELECT id FROM courses WHERE name = 'Sales Mastery'));

-- 3. Subcategories
INSERT INTO subcategories (title, content, category_id, sort_order) VALUES ('Client Journey', '', (SELECT id FROM categories WHERE title = 'Introduction' AND course_id = (SELECT id FROM courses WHERE name = 'Sales Mastery') LIMIT 1), 0);
INSERT INTO subcategories (title, content, category_id, sort_order) VALUES ('Rapport & Needs', '', (SELECT id FROM categories WHERE title = 'CRM' AND course_id = (SELECT id FROM courses WHERE name = 'Sales Mastery') LIMIT 1), 0);
INSERT INTO subcategories (title, content, category_id, sort_order) VALUES ('Elicit & Outcome', '', (SELECT id FROM categories WHERE title = 'ECHO' AND course_id = (SELECT id FROM courses WHERE name = 'Sales Mastery') LIMIT 1), 0);
INSERT INTO subcategories (title, content, category_id, sort_order) VALUES ('Product Presentation', '', (SELECT id FROM categories WHERE title = 'Product' AND course_id = (SELECT id FROM courses WHERE name = 'Sales Mastery') LIMIT 1), 0);
INSERT INTO subcategories (title, content, category_id, sort_order) VALUES ('Product Presentation', '', (SELECT id FROM categories WHERE title = 'CROP' AND course_id = (SELECT id FROM courses WHERE name = 'Sales Mastery') LIMIT 1), 0);
INSERT INTO subcategories (title, content, category_id, sort_order) VALUES ('Objection Handling', '', (SELECT id FROM categories WHERE title = 'GORA' AND course_id = (SELECT id FROM courses WHERE name = 'Sales Mastery') LIMIT 1), 0);
INSERT INTO subcategories (title, content, category_id, sort_order) VALUES ('High Jewel Preparation', '', (SELECT id FROM categories WHERE title = 'CRM' AND course_id = (SELECT id FROM courses WHERE name = 'Sales Mastery') LIMIT 1), 1);
INSERT INTO subcategories (title, content, category_id, sort_order) VALUES ('Diamond Sales Process', '', (SELECT id FROM categories WHERE title = 'ECHO' AND course_id = (SELECT id FROM courses WHERE name = 'Sales Mastery') LIMIT 1), 1);
INSERT INTO subcategories (title, content, category_id, sort_order) VALUES ('CRM & Client Visits', '', (SELECT id FROM categories WHERE title = 'CRM' AND course_id = (SELECT id FROM courses WHERE name = 'Sales Mastery') LIMIT 1), 2);
INSERT INTO subcategories (title, content, category_id, sort_order) VALUES ('Sales Allocating', '', (SELECT id FROM categories WHERE title = 'RLS' AND course_id = (SELECT id FROM courses WHERE name = 'Sales Mastery') LIMIT 1), 0);
INSERT INTO subcategories (title, content, category_id, sort_order) VALUES ('Diamond Service', '', (SELECT id FROM categories WHERE title = 'CRM' AND course_id = (SELECT id FROM courses WHERE name = 'Sales Mastery') LIMIT 1), 3);
INSERT INTO subcategories (title, content, category_id, sort_order) VALUES ('Quality Preparation', '', (SELECT id FROM categories WHERE title = 'CRM' AND course_id = (SELECT id FROM courses WHERE name = 'Sales Mastery') LIMIT 1), 4);
INSERT INTO subcategories (title, content, category_id, sort_order) VALUES ('Teams Roles and Titles', '', (SELECT id FROM categories WHERE title = 'Conclusion' AND course_id = (SELECT id FROM courses WHERE name = 'Sales Mastery') LIMIT 1), 0);
INSERT INTO subcategories (title, content, category_id, sort_order) VALUES ('Exchange Policy', '', (SELECT id FROM categories WHERE title = 'Conclusion' AND course_id = (SELECT id FROM courses WHERE name = 'Sales Mastery') LIMIT 1), 1);

-- 4. Training Tasks
INSERT INTO training_tasks (title, subcategory_id, trainer_type, modality, role_level, priority_level, tags, sort_order) VALUES ('Review the Client Journey map with your manager to understand how to guide clients through each stage of the sales process', (SELECT id FROM subcategories WHERE title = 'Client Journey' AND category_id = (SELECT id FROM categories WHERE title = 'Introduction' AND course_id = (SELECT id FROM courses WHERE name = 'Sales Mastery') LIMIT 1) LIMIT 1), 'Self Directed', '', '', '', '{}', 0);
INSERT INTO training_task_content (training_task_id, type, title, url, sort_order) VALUES ((SELECT id FROM training_tasks WHERE title = 'Review the Client Journey map with your manager to understand how to guide clients through each stage of the sales process' LIMIT 1), 'webpage', 'Link', 'https://canturi-squad.monday.com/protected_static/27728372/resources/64052620/CANTURI SALES JOURNEY.jpg', 0);
INSERT INTO training_tasks (title, subcategory_id, trainer_type, modality, role_level, priority_level, tags, sort_order) VALUES ('Watch the Melbourne GRIN presentation to build skills in gaining rapport and investigating client needs, reinforced with real-life stories', (SELECT id FROM subcategories WHERE title = 'Rapport & Needs' AND category_id = (SELECT id FROM categories WHERE title = 'CRM' AND course_id = (SELECT id FROM courses WHERE name = 'Sales Mastery') LIMIT 1) LIMIT 1), 'Self Directed', '', '', '', '{}', 0);
INSERT INTO training_task_content (training_task_id, type, title, url, sort_order) VALUES ((SELECT id FROM training_tasks WHERE title = 'Watch the Melbourne GRIN presentation to build skills in gaining rapport and investigating client needs, reinforced with real-life stories' LIMIT 1), 'webpage', 'Link', 'https://vimeo.com/716626427', 0);
INSERT INTO training_tasks (title, subcategory_id, trainer_type, modality, role_level, priority_level, tags, sort_order) VALUES ('Watch the Elicit Criteria + Harness Outcome Training video to learn how to uncover client outcomes and apply the ECHO framework using real stories and Google review examples', (SELECT id FROM subcategories WHERE title = 'Elicit & Outcome' AND category_id = (SELECT id FROM categories WHERE title = 'ECHO' AND course_id = (SELECT id FROM courses WHERE name = 'Sales Mastery') LIMIT 1) LIMIT 1), 'Self Directed', '', '', '', '{}', 0);
INSERT INTO training_task_content (training_task_id, type, title, url, sort_order) VALUES ((SELECT id FROM training_tasks WHERE title = 'Watch the Elicit Criteria + Harness Outcome Training video to learn how to uncover client outcomes and apply the ECHO framework using real stories and Google review examples' LIMIT 1), 'webpage', 'Link', 'https://vimeo.com/738810083', 0);
INSERT INTO training_tasks (title, subcategory_id, trainer_type, modality, role_level, priority_level, tags, sort_order) VALUES ('Watch the Product Presentation Vimeo to understand the full offer process — including product display, gloves procedure, narrowing down selection, and key tips from Trish and Lucia', (SELECT id FROM subcategories WHERE title = 'Product Presentation' AND category_id = (SELECT id FROM categories WHERE title = 'Product' AND course_id = (SELECT id FROM courses WHERE name = 'Sales Mastery') LIMIT 1) LIMIT 1), 'Self Directed', '', '', '', '{}', 0);
INSERT INTO training_task_content (training_task_id, type, title, url, sort_order) VALUES ((SELECT id FROM training_tasks WHERE title = 'Watch the Product Presentation Vimeo to understand the full offer process — including product display, gloves procedure, narrowing down selection, and key tips from Trish and Lucia' LIMIT 1), 'webpage', 'PW: Prod333', 'https://vimeo.com/1007535352', 0);
INSERT INTO training_tasks (title, subcategory_id, trainer_type, modality, role_level, priority_level, tags, sort_order) VALUES ('Watch the CROP Zoom video to practise checking rapport and presenting the product offer confidently', (SELECT id FROM subcategories WHERE title = 'Product Presentation' AND category_id = (SELECT id FROM categories WHERE title = 'CROP' AND course_id = (SELECT id FROM courses WHERE name = 'Sales Mastery') LIMIT 1) LIMIT 1), 'Self Directed', '', '', '', '{}', 0);
INSERT INTO training_task_content (training_task_id, type, title, url, sort_order) VALUES ((SELECT id FROM training_tasks WHERE title = 'Watch the CROP Zoom video to practise checking rapport and presenting the product offer confidently' LIMIT 1), 'webpage', 'PW: CROP232', 'https://vimeo.com/757793538', 0);
INSERT INTO training_tasks (title, subcategory_id, trainer_type, modality, role_level, priority_level, tags, sort_order) VALUES ('Review the Canturi Product Presentation Standards to learn how to present jewels correctly and expand on client-facing presentation tips', (SELECT id FROM subcategories WHERE title = 'Product Presentation' AND category_id = (SELECT id FROM categories WHERE title = 'Product' AND course_id = (SELECT id FROM courses WHERE name = 'Sales Mastery') LIMIT 1) LIMIT 1), 'Self Directed', '', '', '', '{}', 1);
INSERT INTO training_task_content (training_task_id, type, title, url, sort_order) VALUES ((SELECT id FROM training_tasks WHERE title = 'Review the Canturi Product Presentation Standards to learn how to present jewels correctly and expand on client-facing presentation tips' LIMIT 1), 'text', 'Text', '', 0);
INSERT INTO training_tasks (title, subcategory_id, trainer_type, modality, role_level, priority_level, tags, sort_order) VALUES ('Watch the GORA Vimeo Presentation to learn how to gather objections and request the next action from the client', (SELECT id FROM subcategories WHERE title = 'Objection Handling' AND category_id = (SELECT id FROM categories WHERE title = 'GORA' AND course_id = (SELECT id FROM courses WHERE name = 'Sales Mastery') LIMIT 1) LIMIT 1), 'Self Directed', '', '', '', '{}', 0);
INSERT INTO training_task_content (training_task_id, type, title, url, sort_order) VALUES ((SELECT id FROM training_tasks WHERE title = 'Watch the GORA Vimeo Presentation to learn how to gather objections and request the next action from the client' LIMIT 1), 'webpage', 'PW: GORA747', 'https://vimeo.com/774927067', 0);
INSERT INTO training_tasks (title, subcategory_id, trainer_type, modality, role_level, priority_level, tags, sort_order) VALUES ('Watch the FUEL Overview and Melbourne Breakthroughs video to understand the 2022 sales breakthroughs and how to apply FUEL principles in client conversations', (SELECT id FROM subcategories WHERE title = 'Objection Handling' AND category_id = (SELECT id FROM categories WHERE title = 'GORA' AND course_id = (SELECT id FROM courses WHERE name = 'Sales Mastery') LIMIT 1) LIMIT 1), 'Self Directed', '', '', '', '{}', 1);
INSERT INTO training_task_content (training_task_id, type, title, url, sort_order) VALUES ((SELECT id FROM training_tasks WHERE title = 'Watch the FUEL Overview and Melbourne Breakthroughs video to understand the 2022 sales breakthroughs and how to apply FUEL principles in client conversations' LIMIT 1), 'webpage', 'PW: FUEL000', 'https://vimeo.com/777231069', 0);
INSERT INTO training_tasks (title, subcategory_id, trainer_type, modality, role_level, priority_level, tags, sort_order) VALUES ('Watch the GORA Positive Mindset video to develop a client-focused mindset — covering listening, adding value, seeing the client''s perspective, clarifying objections, and recognising buying signals', (SELECT id FROM subcategories WHERE title = 'Objection Handling' AND category_id = (SELECT id FROM categories WHERE title = 'GORA' AND course_id = (SELECT id FROM courses WHERE name = 'Sales Mastery') LIMIT 1) LIMIT 1), 'Self Directed', '', '', '', '{}', 2);
INSERT INTO training_task_content (training_task_id, type, title, url, sort_order) VALUES ((SELECT id FROM training_tasks WHERE title = 'Watch the GORA Positive Mindset video to develop a client-focused mindset — covering listening, adding value, seeing the client''s perspective, clarifying objections, and recognising buying signals' LIMIT 1), 'webpage', 'PW: Go456', 'https://vimeo.com/766722832', 0);
INSERT INTO training_tasks (title, subcategory_id, trainer_type, modality, role_level, priority_level, tags, sort_order) VALUES ('Watch the GORA Asking Questions video to learn how to discover and manage objections through skilled questioning, using Leah''s Cubism ring as a real-life example', (SELECT id FROM subcategories WHERE title = 'Objection Handling' AND category_id = (SELECT id FROM categories WHERE title = 'GORA' AND course_id = (SELECT id FROM courses WHERE name = 'Sales Mastery') LIMIT 1) LIMIT 1), 'Self Directed', '', '', '', '{}', 3);
INSERT INTO training_task_content (training_task_id, type, title, url, sort_order) VALUES ((SELECT id FROM training_tasks WHERE title = 'Watch the GORA Asking Questions video to learn how to discover and manage objections through skilled questioning, using Leah''s Cubism ring as a real-life example' LIMIT 1), 'webpage', 'PW: Go457', 'https://vimeo.com/766742626', 0);
INSERT INTO training_tasks (title, subcategory_id, trainer_type, modality, role_level, priority_level, tags, sort_order) VALUES ('Watch the GORA Reframing + Story Telling video to learn how to reframe objections positively, use storytelling, and turn objections into opportunities', (SELECT id FROM subcategories WHERE title = 'Objection Handling' AND category_id = (SELECT id FROM categories WHERE title = 'GORA' AND course_id = (SELECT id FROM courses WHERE name = 'Sales Mastery') LIMIT 1) LIMIT 1), 'Self Directed', '', '', '', '{}', 4);
INSERT INTO training_task_content (training_task_id, type, title, url, sort_order) VALUES ((SELECT id FROM training_tasks WHERE title = 'Watch the GORA Reframing + Story Telling video to learn how to reframe objections positively, use storytelling, and turn objections into opportunities' LIMIT 1), 'webpage', 'PW: Go458', 'https://vimeo.com/766745624', 0);
INSERT INTO training_tasks (title, subcategory_id, trainer_type, modality, role_level, priority_level, tags, sort_order) VALUES ('Watch the GORA Responses video to practise responding to classic hesitations such as ''I want to think about it'', ''I want to look around'', and ''I''m going to go for a coffee''', (SELECT id FROM subcategories WHERE title = 'Objection Handling' AND category_id = (SELECT id FROM categories WHERE title = 'GORA' AND course_id = (SELECT id FROM courses WHERE name = 'Sales Mastery') LIMIT 1) LIMIT 1), 'Self Directed', '', '', '', '{}', 5);
INSERT INTO training_task_content (training_task_id, type, title, url, sort_order) VALUES ((SELECT id FROM training_tasks WHERE title = 'Watch the GORA Responses video to practise responding to classic hesitations such as ''I want to think about it'', ''I want to look around'', and ''I''m going to go for a coffee''' LIMIT 1), 'webpage', 'PW: Go459', 'https://vimeo.com/768290138', 0);
INSERT INTO training_tasks (title, subcategory_id, trainer_type, modality, role_level, priority_level, tags, sort_order) VALUES ('Watch the GORA Never Assume video to practise using the mirror technique, moving around the boutique, and inviting a colleague for a second opinion', (SELECT id FROM subcategories WHERE title = 'Objection Handling' AND category_id = (SELECT id FROM categories WHERE title = 'GORA' AND course_id = (SELECT id FROM courses WHERE name = 'Sales Mastery') LIMIT 1) LIMIT 1), 'Self Directed', '', '', '', '{}', 6);
INSERT INTO training_task_content (training_task_id, type, title, url, sort_order) VALUES ((SELECT id FROM training_tasks WHERE title = 'Watch the GORA Never Assume video to practise using the mirror technique, moving around the boutique, and inviting a colleague for a second opinion' LIMIT 1), 'webpage', 'PW: Go460', 'https://vimeo.com/768292634', 0);
INSERT INTO training_tasks (title, subcategory_id, trainer_type, modality, role_level, priority_level, tags, sort_order) VALUES ('Watch the GORA Time Frame video to learn how to frame your actions confidently and handle ''I''m in no rush'' situations', (SELECT id FROM subcategories WHERE title = 'Objection Handling' AND category_id = (SELECT id FROM categories WHERE title = 'GORA' AND course_id = (SELECT id FROM courses WHERE name = 'Sales Mastery') LIMIT 1) LIMIT 1), 'Self Directed', '', '', '', '{}', 7);
INSERT INTO training_task_content (training_task_id, type, title, url, sort_order) VALUES ((SELECT id FROM training_tasks WHERE title = 'Watch the GORA Time Frame video to learn how to frame your actions confidently and handle ''I''m in no rush'' situations' LIMIT 1), 'webpage', 'PW: Go461', 'https://vimeo.com/768296240', 0);
INSERT INTO training_tasks (title, subcategory_id, trainer_type, modality, role_level, priority_level, tags, sort_order) VALUES ('Watch the GORA Responses snippet to practise quick, confident responses when a client says ''I want to look around''', (SELECT id FROM subcategories WHERE title = 'Objection Handling' AND category_id = (SELECT id FROM categories WHERE title = 'GORA' AND course_id = (SELECT id FROM courses WHERE name = 'Sales Mastery') LIMIT 1) LIMIT 1), 'Self Directed', '', '', '', '{}', 8);
INSERT INTO training_task_content (training_task_id, type, title, url, sort_order) VALUES ((SELECT id FROM training_tasks WHERE title = 'Watch the GORA Responses snippet to practise quick, confident responses when a client says ''I want to look around''' LIMIT 1), 'webpage', 'PW: Go462', 'https://vimeo.com/768298830', 0);
INSERT INTO training_tasks (title, subcategory_id, trainer_type, modality, role_level, priority_level, tags, sort_order) VALUES ('Watch the GORA Mindset snippet to reinforce a positive approach to objections and strengthen your mindset before client interactions', (SELECT id FROM subcategories WHERE title = 'Objection Handling' AND category_id = (SELECT id FROM categories WHERE title = 'GORA' AND course_id = (SELECT id FROM courses WHERE name = 'Sales Mastery') LIMIT 1) LIMIT 1), 'Self Directed', '', '', '', '{}', 9);
INSERT INTO training_task_content (training_task_id, type, title, url, sort_order) VALUES ((SELECT id FROM training_tasks WHERE title = 'Watch the GORA Mindset snippet to reinforce a positive approach to objections and strengthen your mindset before client interactions' LIMIT 1), 'webpage', 'PW: Go463', 'https://vimeo.com/768300049', 0);
INSERT INTO training_tasks (title, subcategory_id, trainer_type, modality, role_level, priority_level, tags, sort_order) VALUES ('Watch the GORA Types of Objections snippet and review the Objections Mindmap to understand objection categories, including design-related responses', (SELECT id FROM subcategories WHERE title = 'Objection Handling' AND category_id = (SELECT id FROM categories WHERE title = 'GORA' AND course_id = (SELECT id FROM courses WHERE name = 'Sales Mastery') LIMIT 1) LIMIT 1), 'Self Directed', '', '', '', '{}', 10);
INSERT INTO training_task_content (training_task_id, type, title, url, sort_order) VALUES ((SELECT id FROM training_tasks WHERE title = 'Watch the GORA Types of Objections snippet and review the Objections Mindmap to understand objection categories, including design-related responses' LIMIT 1), 'webpage', 'PW: Go464', 'https://vimeo.com/768852814', 0);
INSERT INTO training_tasks (title, subcategory_id, trainer_type, modality, role_level, priority_level, tags, sort_order) VALUES ('Watch the GORA Price snippet to understand how to handle price-related objections with integrity and confidence', (SELECT id FROM subcategories WHERE title = 'Objection Handling' AND category_id = (SELECT id FROM categories WHERE title = 'GORA' AND course_id = (SELECT id FROM courses WHERE name = 'Sales Mastery') LIMIT 1) LIMIT 1), 'Self Directed', '', '', '', '{}', 11);
INSERT INTO training_task_content (training_task_id, type, title, url, sort_order) VALUES ((SELECT id FROM training_tasks WHERE title = 'Watch the GORA Price snippet to understand how to handle price-related objections with integrity and confidence' LIMIT 1), 'webpage', 'PW: Go465', 'https://vimeo.com/768853345', 0);
INSERT INTO training_tasks (title, subcategory_id, trainer_type, modality, role_level, priority_level, tags, sort_order) VALUES ('Watch Anna''s Zoom video to learn how to prepare for high-jewel client appointments, drawing inspiration from the Island Luxe Liquid Ring example and requesting the next action', (SELECT id FROM subcategories WHERE title = 'High Jewel Preparation' AND category_id = (SELECT id FROM categories WHERE title = 'CRM' AND course_id = (SELECT id FROM courses WHERE name = 'Sales Mastery') LIMIT 1) LIMIT 1), 'Self Directed', '', '', '', '{}', 0);
INSERT INTO training_task_content (training_task_id, type, title, url, sort_order) VALUES ((SELECT id FROM training_tasks WHERE title = 'Watch Anna''s Zoom video to learn how to prepare for high-jewel client appointments, drawing inspiration from the Island Luxe Liquid Ring example and requesting the next action' LIMIT 1), 'webpage', 'Link', 'https://vimeo.com/1113795951', 0);
INSERT INTO training_tasks (title, subcategory_id, trainer_type, modality, role_level, priority_level, tags, sort_order) VALUES ('Watch the 2 Part Process video to learn a clear, simple approach to selling a Diamond ring using Anna''s RLS framework', (SELECT id FROM subcategories WHERE title = 'Diamond Sales Process' AND category_id = (SELECT id FROM categories WHERE title = 'ECHO' AND course_id = (SELECT id FROM courses WHERE name = 'Sales Mastery') LIMIT 1) LIMIT 1), 'Self Directed', '', '', '', '{}', 0);
INSERT INTO training_task_content (training_task_id, type, title, url, sort_order) VALUES ((SELECT id FROM training_tasks WHERE title = 'Watch the 2 Part Process video to learn a clear, simple approach to selling a Diamond ring using Anna''s RLS framework' LIMIT 1), 'webpage', 'Link', 'https://vimeo.com/1122113622', 0);
INSERT INTO training_tasks (title, subcategory_id, trainer_type, modality, role_level, priority_level, tags, sort_order) VALUES ('Watch the ECHO + 2 Part Process video, combining the Melbourne Elicit Criteria presentation with Anna''s RLS process — can be watched in two sittings', (SELECT id FROM subcategories WHERE title = 'Diamond Sales Process' AND category_id = (SELECT id FROM categories WHERE title = 'ECHO' AND course_id = (SELECT id FROM courses WHERE name = 'Sales Mastery') LIMIT 1) LIMIT 1), 'Self Directed', '', '', '', '{}', 1);
INSERT INTO training_task_content (training_task_id, type, title, url, sort_order) VALUES ((SELECT id FROM training_tasks WHERE title = 'Watch the ECHO + 2 Part Process video, combining the Melbourne Elicit Criteria presentation with Anna''s RLS process — can be watched in two sittings' LIMIT 1), 'webpage', 'Link', 'https://vimeo.com/video/738810083', 0);
INSERT INTO training_tasks (title, subcategory_id, trainer_type, modality, role_level, priority_level, tags, sort_order) VALUES ('Watch the full ECHO + Selling a Diamond Ring video to consolidate the Melbourne Elicit Criteria presentation with the Anna RLS 2-part process end-to-end', (SELECT id FROM subcategories WHERE title = 'Diamond Sales Process' AND category_id = (SELECT id FROM categories WHERE title = 'ECHO' AND course_id = (SELECT id FROM courses WHERE name = 'Sales Mastery') LIMIT 1) LIMIT 1), 'Self Directed', '', '', '', '{}', 2);
INSERT INTO training_task_content (training_task_id, type, title, url, sort_order) VALUES ((SELECT id FROM training_tasks WHERE title = 'Watch the full ECHO + Selling a Diamond Ring video to consolidate the Melbourne Elicit Criteria presentation with the Anna RLS 2-part process end-to-end' LIMIT 1), 'webpage', 'Link', 'https://vimeo.com/video/738810083', 0);
INSERT INTO training_tasks (title, subcategory_id, trainer_type, modality, role_level, priority_level, tags, sort_order) VALUES ('Watch the CRM Visit and Real Life Stories video to understand how to conduct effective CRM visits, with examples from Ultrasonics and real client stories', (SELECT id FROM subcategories WHERE title = 'CRM & Client Visits' AND category_id = (SELECT id FROM categories WHERE title = 'CRM' AND course_id = (SELECT id FROM courses WHERE name = 'Sales Mastery') LIMIT 1) LIMIT 1), 'Self Directed', '', '', '', '{}', 0);
INSERT INTO training_task_content (training_task_id, type, title, url, sort_order) VALUES ((SELECT id FROM training_tasks WHERE title = 'Watch the CRM Visit and Real Life Stories video to understand how to conduct effective CRM visits, with examples from Ultrasonics and real client stories' LIMIT 1), 'webpage', 'Link', 'https://vimeo.com/707635580', 0);
INSERT INTO training_tasks (title, subcategory_id, trainer_type, modality, role_level, priority_level, tags, sort_order) VALUES ('Watch the Brisbane RLS Sales Allocating Zoom to understand how sales are allocated nationally at Canturi, and note your 3 top takeaways to email to Leah and Vicky', (SELECT id FROM subcategories WHERE title = 'Sales Allocating' AND category_id = (SELECT id FROM categories WHERE title = 'RLS' AND course_id = (SELECT id FROM courses WHERE name = 'Sales Mastery') LIMIT 1) LIMIT 1), 'Self Directed', '', '', '', '{}', 0);
INSERT INTO training_task_content (training_task_id, type, title, url, sort_order) VALUES ((SELECT id FROM training_tasks WHERE title = 'Watch the Brisbane RLS Sales Allocating Zoom to understand how sales are allocated nationally at Canturi, and note your 3 top takeaways to email to Leah and Vicky' LIMIT 1), 'webpage', 'PW: Zoom258', 'https://vimeo.com/996561520', 0);
INSERT INTO training_tasks (title, subcategory_id, trainer_type, modality, role_level, priority_level, tags, sort_order) VALUES ('Watch Silvia''s Diamond Ring Sale from Email video to learn how to sell diamonds from an email enquiry, understanding important criteria and Natural vs Lab diamond differences', (SELECT id FROM subcategories WHERE title = 'Diamond Service' AND category_id = (SELECT id FROM categories WHERE title = 'CRM' AND course_id = (SELECT id FROM courses WHERE name = 'Sales Mastery') LIMIT 1) LIMIT 1), 'Self Directed', '', '', '', '{}', 0);
INSERT INTO training_task_content (training_task_id, type, title, url, sort_order) VALUES ((SELECT id FROM training_tasks WHERE title = 'Watch Silvia''s Diamond Ring Sale from Email video to learn how to sell diamonds from an email enquiry, understanding important criteria and Natural vs Lab diamond differences' LIMIT 1), 'webpage', 'Link', 'https://vimeo.com/977409822', 0);
INSERT INTO training_tasks (title, subcategory_id, trainer_type, modality, role_level, priority_level, tags, sort_order) VALUES ('Watch Silvia ''The Expert'' video to learn how to lead Diamond selection conversations via email communication and video call', (SELECT id FROM subcategories WHERE title = 'Diamond Service' AND category_id = (SELECT id FROM categories WHERE title = 'CRM' AND course_id = (SELECT id FROM courses WHERE name = 'Sales Mastery') LIMIT 1) LIMIT 1), 'Self Directed', '', '', '', '{}', 1);
INSERT INTO training_task_content (training_task_id, type, title, url, sort_order) VALUES ((SELECT id FROM training_tasks WHERE title = 'Watch Silvia ''The Expert'' video to learn how to lead Diamond selection conversations via email communication and video call' LIMIT 1), 'webpage', 'Link', 'https://vimeo.com/1113794149', 0);
INSERT INTO training_tasks (title, subcategory_id, trainer_type, modality, role_level, priority_level, tags, sort_order) VALUES ('Review the Quality Preparation Checklist with your manager to understand how our best consultants prepare before client interactions — complete the open task', (SELECT id FROM subcategories WHERE title = 'Quality Preparation' AND category_id = (SELECT id FROM categories WHERE title = 'CRM' AND course_id = (SELECT id FROM courses WHERE name = 'Sales Mastery') LIMIT 1) LIMIT 1), 'Manager', '', '', '', '{}', 0);
INSERT INTO training_task_content (training_task_id, type, title, url, sort_order) VALUES ((SELECT id FROM training_tasks WHERE title = 'Review the Quality Preparation Checklist with your manager to understand how our best consultants prepare before client interactions — complete the open task' LIMIT 1), 'text', 'Text', '', 0);
INSERT INTO training_tasks (title, subcategory_id, trainer_type, modality, role_level, priority_level, tags, sort_order) VALUES ('Study recent Quality Preparation examples from Vicky, Gillian, and Silvia in the RLS with your manager to model best practice — complete the open task', (SELECT id FROM subcategories WHERE title = 'Quality Preparation' AND category_id = (SELECT id FROM categories WHERE title = 'CRM' AND course_id = (SELECT id FROM courses WHERE name = 'Sales Mastery') LIMIT 1) LIMIT 1), 'Manager', '', '', '', '{}', 1);
INSERT INTO training_task_content (training_task_id, type, title, url, sort_order) VALUES ((SELECT id FROM training_tasks WHERE title = 'Study recent Quality Preparation examples from Vicky, Gillian, and Silvia in the RLS with your manager to model best practice — complete the open task' LIMIT 1), 'text', 'Text', '', 0);
INSERT INTO training_tasks (title, subcategory_id, trainer_type, modality, role_level, priority_level, tags, sort_order) VALUES ('Complete the Quality Preparation Exercise with your manager to elevate the client experience — expand the task as directed', (SELECT id FROM subcategories WHERE title = 'Quality Preparation' AND category_id = (SELECT id FROM categories WHERE title = 'CRM' AND course_id = (SELECT id FROM courses WHERE name = 'Sales Mastery') LIMIT 1) LIMIT 1), 'Manager', '', '', '', '{}', 2);
INSERT INTO training_task_content (training_task_id, type, title, url, sort_order) VALUES ((SELECT id FROM training_tasks WHERE title = 'Complete the Quality Preparation Exercise with your manager to elevate the client experience — expand the task as directed' LIMIT 1), 'text', 'Text', '', 0);
INSERT INTO training_tasks (title, subcategory_id, trainer_type, modality, role_level, priority_level, tags, sort_order) VALUES ('Review Team Roles and Titles with your manager to understand how to hand over enquiries and identify who is best placed to support each client''s needs', (SELECT id FROM subcategories WHERE title = 'Teams Roles and Titles' AND category_id = (SELECT id FROM categories WHERE title = 'Conclusion' AND course_id = (SELECT id FROM courses WHERE name = 'Sales Mastery') LIMIT 1) LIMIT 1), 'Manager', '', '', '', '{}', 0);
INSERT INTO training_task_content (training_task_id, type, title, url, sort_order) VALUES ((SELECT id FROM training_tasks WHERE title = 'Review Team Roles and Titles with your manager to understand how to hand over enquiries and identify who is best placed to support each client''s needs' LIMIT 1), 'webpage', 'Link', 'https://canturi-squad.monday.com/boards/2020331558', 0);
INSERT INTO training_tasks (title, subcategory_id, trainer_type, modality, role_level, priority_level, tags, sort_order) VALUES ('Review the Canturi Exchange Policy with your manager to understand the correct process when the original consultant is not available', (SELECT id FROM subcategories WHERE title = 'Exchange Policy' AND category_id = (SELECT id FROM categories WHERE title = 'Conclusion' AND course_id = (SELECT id FROM courses WHERE name = 'Sales Mastery') LIMIT 1) LIMIT 1), 'Manager', '', '', '', '{}', 0);
INSERT INTO training_task_content (training_task_id, type, title, url, sort_order) VALUES ((SELECT id FROM training_tasks WHERE title = 'Review the Canturi Exchange Policy with your manager to understand the correct process when the original consultant is not available' LIMIT 1), 'webpage', 'Link', 'https://cdrdpl86.com/credit%2Fexchange-policy', 0);
